os: linux
dist: bionic
cache: ccache
language: cpp

addons:
  apt:
    packages:
      - clang-format

jobs:
 include:
  - env: [JOB=build]
    compiler: gcc
    name: Build with gcc

  - env: [JOB=build]
    compiler: clang
    name: Build with clang

  - env: [JOB=clang-format]
    name: Check code style with clang-format

before_install:
  - if test $JOB == build; then sudo add-apt-repository -y ppa:beineri/opt-qt-5.14.0-bionic && sudo apt-get update -qq; fi

install:
  - if test $JOB == build; then sudo apt-get install -qq qt514base qt514serialport && source /opt/qt514/bin/qt514-env.sh; fi

script:
  - | 
      if test $JOB == build; then
      mkdir _build _install
      cd _build 
      cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$PWD/../_install ..
      make VERBOSE=1
      make install
      fi

  - | 
      if test $JOB == clang-format; then
      shopt -s globstar
      clang-format -i **/*.h **/*.cpp
      git diff --exit-code
      fi

notifications:
  email:
    on_success: never
    on_failure: never

deploy:
  provider: releases
  file_glob: true
  file: $TRAVIS_BUILD_DIR/_install/**/*
  draft: true
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
    condition: $TRAVIS_COMPILER = clang
  token:
    secure: SILYFhJ5IMFiq6CsI2JSMJ7Nn2XEZ6wDAKh+fWYcCNVQhMK1kml5HLZBjH0/NoFqv1LitFhepmzFcOF5TQTN6kU3OqisnsNSAayJBvuPGQY/PPZIDcHuVnyqUDbxfQk5th+sPZWf5iImX+domqNlrSGVr9MKgP3/4DI1TVHe4auH6Q6tvW1tzePDKHczAMiHVKgfNnL+OCNlCng+3yBA8o3dGAqMs3FlvC2XwhWvAIYHtilyqsWjCzXe06c2CeOC35A+xl7c6HKRuoqa4j6g+l4DbI3g7q8Z2fNe2nq6RqBkhELieYSzUUZ5ID6lszK7O/UBH8fNEgLNabiu1qT7qQ84GZprqoF71rIAhBRILyNok8LT+s2FPAlBNa8gUngpCMwGEpFE32+mT76N8MizzHEVzDgWxeB/Tebrr2tCVpynaic8P+OqppYzj1erux//2bUx9sIAI2mvAdbHM2gPPl93WQ/YKu6CMqfnzE/KHsBkMN2A7ANroEAsg4qplnqrEPHu3vmMKuC/84a0dLagR/5Xo0i7rpuNBuMbdVylI3wvzFSvJ+AGnAEQqJCtOPZZEmxh1j2f7UsC/4q9CN86RoqJVsLaSYxC/C7vxTcxHPRhWNST+RyUi7uwPVSVa9BLssBoFGFjxb/G00RlsLWMaexGW+UhrSqkCLXiiDYDwVk=
