name: C/C++ CI

on: [push]

jobs:

  build:
    strategy:
        matrix:
          cc: [ gcc, clang ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: docker://lpenz/ghaction-cmake:latest
        with:
          dependencies: "qtbase5-dev libqt5serialport5-dev"
          cc: ${{ matrix.cc }}

  clang-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: docker://lpenz/ghaction-cmake:latest
        with:
          analyzer: clang-format
